# Generated by Django 4.1 on 2022-08-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
